# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 01:42
from __future__ import unicode_literals

import art.models
import datetime
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 250 characters', max_length=250)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('art_type', models.IntegerField(choices=[(1, 'Photography'), (2, 'Modelling'), (3, 'Sketches')], default=3)),
                ('tags', tagging.fields.TagField(blank=True, help_text='Seperate tags with spaces.', max_length=255)),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('image_highres', models.ImageField(upload_to=art.models.Art.get_upload_path_high)),
                ('image_lowres', models.ImageField(upload_to=art.models.Art.get_upload_path_low)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
