# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.IntegerField(choices=[(0, 'Photography'), (1, 'Modelling'), (2, 'Sketches')], default=2),
        ),
    ]
