# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20161002_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Max 100 characters', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art_Category'),
        ),
    ]
