# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20161002_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
