# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 23:47
from __future__ import unicode_literals

import art.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_art_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='image_highres',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.Art.get_upload_path_high),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_lowres',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.Art.get_upload_path_low),
        ),
        migrations.AddField(
            model_name='art_url',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art'),
        ),
    ]
