# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20170618_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_category',
            name='slug',
            field=models.SlugField(default='category-name', help_text='Suggested value automatically generated from title. Must be unique.', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True),
        ),
    ]
