# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_auto_20170620_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='art',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art_url',
            name='body_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
