# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_auto_20170628_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_url',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
