# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20170628_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
