# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters', max_length=250)),
                ('excerpt', models.TextField(help_text='A short summary of the entry.')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('excerpt_html', models.TextField(blank=True, editable=False)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('enable_comments', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique_for_date='pub_date')),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=1, help_text='Only entries with live status will be publicly displayed.')),
                ('tags', tagging.fields.TagField(blank=True, help_text='Seperate tags with spaces.', max_length=255)),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
