# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.')),
                ('about', models.TextField()),
                ('about_html', models.TextField(blank=True, editable=False)),
                ('excerpt', models.TextField(help_text='A short summary of the project.')),
                ('excerpt_html', models.TextField(blank=True, editable=False)),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
